language: node_js
node_js: stable
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  # firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test --module-resolution=node --npm --plugin local
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm --plugin sauce --job-name
    "paper-chip-input:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
    fi
env:
  global:
    - secure: >-
        SUq9JfoMN8v4MUzF2mb9nKVDMIOIWfu0fADvXiDFjBuPgmEjxu4ArBsRUax/9HWQPoud/N7YIIxDa8SsdgF8GPSa3oBOcEbxjFq1O6Wu+qY2/GEvhZEPjgfSpuk1Ukc4MooRocOXiU4sQ002atiO3U9xa3jEMCc9xsdpWwoyjJJvuqfLn++OjJ2H0hPw86Wt+JX0MCXTbP1vm1VsWBWK+QG/+ju7qQbMKgekiYjXHokhA35SWV8q0ALFXtti7VG/+UBEHqci3M4dYaHCUNUp5qe89bXo+QkUlVRIUx5fWaSJnXl9RSahuPDMylGtg31x0ESLASCYtrNNXmxDBo5S7kOzIAwjfU/q0gBfT4jctYOdIUiTff/beGv2aVm6gpePxtxDQp+XCYz5SJA2Dy1Nxwa/5jneaI389R/C9aglu6t9WBF14oeWxti/YgpusDMQF0g04ClxahyGDFDyOyNzo2Gsy1FDqnkV2pW/B1MEbKc6jQNaye/Qs93ozq5BWoDFOYqkT7wCAR1OLXFnEUN2Z+ZwAv0i8NIziZwgIaaAQFZyHDUgYy0khq0VCpQIWD4gHwtLESUkZLxDOlWgqlEkqz6ux26isLDU4JnkAy0E9ZVaDRtWVHDrPFR3GHr36MdlG533b73s5Q88ZcTsEv0GIvbL5W0WPCNe7oFnY5S361M=
    - secure: >-
        K43uZajrzo9zCIv5cBg56clEzl1XTmeliNNucKyXgAtr5v+mQYM0bI4H92PgRXAomJwnxdexPyK39ejzbVlSoLSXm7CHWFhp7J1K45xzmlxS3n6XJaRLWQsfTnAYozL+nbU8INH5OBp/NYumN/sKIelEt1qqQYsYoNoDusD5HTqrOHwk0r/xf4KF9KOWKY0q4vGlC1aS1jK3B9KYkuOPTkMj7yync9avISHuMkcmnhTn9zHfNa0R57lyv9PInPU0BEGq9twarM3jmKfHSohOABvu1Jk3z1gvIPyOonij9O8rXU9e8DxRM3KGotvhuWbA+WxX9EUDedJSZZqqZwssFb/0nLlW3zLjakkH9vec5HmUQSeIWFpYmqAu3JdSUb3KGDF9q5NYACDg5ZguXYVish4gTP9sY3ji4WES100Cd+yyxvWdrDhv47jNvTx87TONmt0rrGue6EkZEEqZ2ekmrB6UtNfsGRaG2LjwaIGzoy7lk54eDlEy4D1CWosIGzPVsK3cigIht7c9XGUfQ9FXTFQFAp+EOzcoxbl2/i8QxyFKYJw6VoTAHonrwuHllKkB4m++p5pDbPADlEtc6Ec8hKA/5SO7mejphd2zwRqSI49qiTqS1ZLwpP3eg2mqgeRGRA38FqhMkdJcQ+/Ua9g2hEgoPYBf+nepFkNJ2LNWJd4=
